cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    demo_user:
      email: kateshdrops@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Forecast Demo
      password: $2b$12$3crZLGX7g9jCN6c0hfoKYO08rW5eL32OzPZk0l72e3U8cDQf4jd/a
      role: admin
    

